services:
  r1:
    build: 
      context: .
      dockerfile: Dockerfile_r1
    stdin_open: true
    tty: true
    cap_add:
      - ALL
    privileged: true
    networks:
      net14:
        ipv4_address: 10.0.14.4 
      net15:
        ipv4_address: 10.0.15.4
      net16:
        ipv4_address: 10.0.16.4

  r2:
    build: 
      context: .
      dockerfile: Dockerfile_r2
    stdin_open: true
    tty: true
    cap_add:
      - ALL
    privileged: true
    networks:
      net15:
        ipv4_address: 10.0.15.3  
      net17:
        ipv4_address: 10.0.17.3

  r3:
    build: 
      context: .
      dockerfile: Dockerfile_r3
    stdin_open: true
    tty: true
    cap_add:
      - ALL
    privileged: true
    networks:
      net17:
        ipv4_address: 10.0.17.4
      net18:
        ipv4_address: 10.0.18.4
      net19:
        ipv4_address: 10.0.19.4

  r4:
    build: 
      context: .
      dockerfile: Dockerfile_r3
    stdin_open: true
    tty: true
    cap_add:
      - ALL
    privileged: true
    networks:
      net18:
        ipv4_address: 10.0.18.3
      net16:
        ipv4_address: 10.0.16.3

  ha:
    build: .
    stdin_open: true
    tty: true
    cap_add:
      - ALL
    privileged: true    
    networks:
      net14:
        ipv4_address: 10.0.14.3

  hb:
    build: .
    stdin_open: true
    tty: true
    cap_add:
      - ALL
    privileged: true    
    networks:
      net19:
        ipv4_address: 10.0.19.3

networks:
  net14:
    ipam:
      driver: default
      config:
        - subnet: 10.0.14.0/24 
  net15:
    ipam:
      driver: default
      config:
        - subnet: 10.0.15.0/24
  net16:
    ipam:
      driver: default
      config:
        - subnet: 10.0.16.0/24
  net17:
    ipam:
      driver: default
      config:
        - subnet: 10.0.17.0/24
  net18:
    ipam:
      driver: default
      config:
        - subnet: 10.0.18.0/24
  net19:
    ipam:
      driver: default
      config:
        - subnet: 10.0.19.0/24
