FROM ubuntu

RUN apt-get update
RUN apt-get -y install bash iproute2 net-tools tcpdump vim iputils-ping curl gnupg lsb-release
RUN apt-get clean


RUN curl -s https://deb.frrouting.org/frr/keys.gpg | tee /usr/share/keyrings/frrouting.gpg > /dev/null 
RUN echo deb [signed-by=/usr/share/keyrings/frrouting.gpg] https://deb.frrouting.org/frr $(lsb_release -s -c) frr-stable | tee -a /etc/apt/sources.list.d/frr.list 
RUN apt-get update 
RUN apt-get install -y frr frr-pythontools


RUN sed -i 's/ospfd=no/ospfd=yes/' /etc/frr/daemons

RUN service frr restart


# Configure OSPF using vtysh
# The below steps are added to configure the router using vtysh
# These steps will configure OSPF, assign router ID, and define networks and OSPF link costs

RUN echo "router ospf\n\
ospf router-id 10.0.14.4\n\
network 10.0.14.0/24 area 0.0.0.0\n\
network 10.0.15.0/24 area 0.0.0.0\n\
exit\n\
interface eth0\n\
ip ospf cost 10\n\
exit" > /etc/frr/frr.conf

# Set the default command to run bash
CMD ["bash"]
